plugins {
    id 'java'
}

group = 'org.example'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.4'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.12.4'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.12.4'
    implementation group: 'com.h2database', name: 'h2', version: '2.2.220'
    implementation(project(":common"))
}

test {
    useJUnitPlatform()
}