#CREATE
create_users_table=CREATE TABLE IF NOT EXISTS Users(\
  id INT PRIMARY_KEY NOT NULL AUTO_INCREMENT, \
  name VARCHAR(50) NOT NULL UNIQUE, \
  deleted BOOLEAN, \
  password VARCHAR(20) NOT NULL));
create_chats_table=CREATE TABLE IF NOT EXISTS Chats(\
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, \
  name VARCHAR(50) NOT NULL, \
  creatorId INT NOT_NULL, \
  deleted BOOLEAN, \
  FOREIGN KEY(creatorId) REFERENCES Users (id));
create_messages_table=CREATE TABLE IF NOT EXISTS Messages(\
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, \
  content VARCHAR(1000) NOT NULL, \
  creationDateTime TIMESTAMP NOT NULL, \
  creatorId INT, \
  chatId INT NOT NULL, \
  deleted BOOLEAN, \
  FOREIGN KEY (creatorId) REFERENCES Users(id) ON DELETE SET NULL,\
  FOREIGN KEY (chatId) REFERENCES Chats(id) ON DELETE CASCADE);
create_users_chats_table=CREATE TABLE IF NOT EXISTS Users_Chats(\
  userId INT NOT NULL,\
  chatId INT NOT NULL,\
  PRIMARY KEY(userId, chatId),\
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,\
  FOREIGN KEY (chatId) REFERENCES Chats(id) ON DELETE CASCADE\
  );
create_sessions_table=CREATE TABLE IF NOT EXISTS Sessions(\
  sessionId INT NOT NULL,\
  userId INT NOT NULL,\
  expiredDate TIMESTAMP NOT NULL, \
  PRIMARY KEY(sessionId),\
  FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE,\
  );
#INSERT
insert_user=INSERT INTO Users VALUES (?, ?);
insert_chat=INSERT INTO Chats VALUES (?, ?, ?);
insert_user_chat=INSERT INTO Users_Chats VALUES (?, ?);
insert_message=INSERT INTO Messages VALUES (?, ?, ?, ?, ?);
insert_session=INSERT INTO Sessions Values(?, ?, ?)
#SELECT
select_user_by_name=SELECT * FROM Users WHERE name = ?;
select_user_login=SELECT COUNT(*) FROM Users WHERE name = ? and password = ?;
select_user_by_id=SELECT * FROM Users WHERE id = ?;
select_session=SELECT * FROM Sessions WHERE sessionId = ?
#UPDATE
update_session_expired_date=UPDATE Sessions SET expiredDate = ? WHERE sessionId = ?
#EXISTS
exists_user_id=SELECT COUNT(*) FROM Users WHERE id = ?
exists_user_name=SELECT COUNT(*) FROM Users WHERE name = ?
